### ISSUE TITLE
Add various functionalities to xades4j

### ISSUE THREAD

**Issue by emmanvg** [luisgoncalves/xades4j#108]
Hi Luis,

I have forked your project and created a couple of code additions with the intention of providing more functionality to your tool. Below are the changes I made:

1. Provide the option in the XAdESverifier.java method perform a secure validation with help from Apache [xmlsec](http://santuario.apache.org/java150releasenotes.html)
     *Note that I used xmlsec 2.0.8, but I noticed a [bug](https://issues.apache.org/jira/browse/SANTUARIO-462) on one of the methods used in xades4j which is reported and will be patched in a later release (2.0.9 or later).

2. I read in a previous thread in which you expressed your reasoning behind not allowing transforms on some Reference elements. My approach allows for one Transform and only one of the Canonicalization Algorithms. Note that, providing a Transform is still totally optional and null can be returned without affecting the signing process.

3. I made a couple of minor changes on the signing procedure to make the Signing process more general. You can provide a certificate or other credential and the hash algorithm specified in the credential will be extracted and used for the SignatureMethod.

I will be opening a merge request shortly which you can review.

Thanks,
Emmanuelle

**Comment by luisgoncalves** [comment]
Hi Emmanuelle,

Any chance you could split the PR into multiple PRs, on per "feature"?

I'm not so sure about the solution using _getCanonicalizationFor..._ methods because there's still no check if that's actually a C14N algorithm. Note that the result of `getCanonicalizationAlgorithmForSignature` method (already existent) is used specifically in a `<ds:CanonicalizationMethod>` element, while yours is used in a `Transform` without further checking. 

Maybe a check similar to the one in [TimeStampDigestInputFactoryImpl](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/utils/TimeStampDigestInputFactoryImpl.java#L51) could be added? The solution there is a bit of a Hack, but there should be a better way to "ask" xmlsec if that's a configured C14N algorithm.

**Comment by emmanvg** [comment]
Hi Luis,

Thanks for the suggestions. Your suggestions make sense. I will remove the current Pull Request and create three separate Pull Requests for each of the functionalities.

Regarding your other solution. Sounds reasonable to change my approach to check if the Transform is actually a C14N algorithm for the one you suggested.

I will perform both suggestions and reference the new pull requests on this issue to keep track of them.

Thanks,
Emmanuelle

**Comment by luisgoncalves** [comment]
Great!

I was looking through the issues and on #32 someone mentions that he used the result of `getCanonicalizationAlgorithmForSignature ` also for KeyInfo and SignedProperties. Would this be an option for you? Both this and adding new methods to the interface are breaking changes...

Anyway, if we go with the option where we check if it is a C14N algorithm, please try to find a better way of doing it :)

**Comment by luisgoncalves** [comment]
Thanks for the contributions!
