### ISSUE TITLE
Custom signature position

### ISSUE THREAD

**Issue by juanp88** [luisgoncalves/xades4j#127]
Hi, I working with the XadesEpes implementation and I'm having troubles giving the signature a custom position in the DOM. I implemented the signer following the XadesEpes test and the wiki, but the signature appears at the end of the document and I need it between a specific tag (one that has an Id="signature").

I have read in the wiki that the sign method should allow the node parameter but the one I have only allow the elemToSign
Can you please point me in the right direction?
Thanks

This is my code.
```
Document doc = getTestDocument();
        Element elemToSign = doc.getDocumentElement();
        System.out.println("inicia el firmador");
        try {
			SignerEPES signer = (SignerEPES)new XadesEpesSigningProfile(kp, policyInfoProvider).newSigner();
			System.out.println("Enveloped");
			new Enveloped(signer).sign(elemToSign);
			outputDocument(doc, "document.signed.epes.xml");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}    
```

**Comment by luisgoncalves** [comment]
You don't see any more options because you're using the `Enveloped` class, which just an utility class for straightforward scenarios. To have additional control (and specify the parent you should use [`XadesSigner`](http://luisgoncalves.github.io/xades4j/javadocs/1.4.0/reference/xades4j/production/XadesSigner.html) directly. Note that you'll need to define the signed data object and the enveloped transform, as needed, assuming you still want to use an enveloped signature. You can see [`Enveloped` source](https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/production/Enveloped.java#L67) or "defining signed resources" in the wiki

**Comment by luisgoncalves** [comment]
This kind of questions should go on S.O. using the `xades4j` tag. Also, please try to dig a bit more and read the javadocs in advance. Thank you.

**Comment by juanp88** [comment]
Thank you, sorry for the troubles.
