### ISSUE TITLE
indicate to which reference if you put the transform

### ISSUE THREAD

**Issue by FuriosoJack** [luisgoncalves/xades4j#136]
In the following example are the references each with a tranform what I want is to be able to specify which reference to add the tranfor to and which is not. so that you do not get transformed just stay with DigestMethod
```
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference Id="xmldsig-be732019-67a4-4942-8e44-bb206ad29abd-ref0" URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>YKobpTh3AwFIk7A1AfUwq+XNH+g=</ds:DigestValue>
</ds:Reference>
<ds:Reference URI="#xmldsig-be732019-67a4-4942-8e44-bb206ad29abd-keyinfo">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>yGBZKbA3nShljIVx87rzgWPBDKY=</ds:DigestValue>
</ds:Reference>
<ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#xmldsig-be732019-67a4-4942-8e44-bb206ad29abd-signedprops">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>TsMFKNhb4L+QBRMeX1/3D06PxFY=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
```

**Comment by luisgoncalves** [comment]
The c14n transform is only added on built-in data object references, namely the reference to `ds:KeyInfo` and the reference to `xades:SignedProperties`.  This is **by design**. The c14n algorithm is the same used for the signature and [can be overridden](https://github.com/luisgoncalves/xades4j/wiki/ChangingAlgorithms).

Note that, as defined on the XML-DSIG spec, even if there isn't an explicit c14n transform in a `ds:Reference`, the processing software must perform canonicalization over the nodeset resulting from the reference. Therefore, the final behavior is the same.

As for application-defined signed data objects - the first reference in your example - you can control which transforms are applied. In you case, you probably used the helper `Enveloped` class, which configures an enveloped signature, which by definition includes a transform as shown above.
