### ISSUE TITLE
IssuerName validation problem "Invalid issue name"

### ISSUE THREAD

**Issue by jaivergh** [luisgoncalves/xades4j#157]
Hi,

I am trying to validate a signature in a xml file, at the validation of the issuername tag:

<X509IssuerName>
C=CO, L=Bogota D.C., O=Andes SCD, OU=Division de certificacion, CN=ROOT CA ANDES SCD S.A., E=info@andesscd.com.co
</X509IssuerName>

Show me the next error:

com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.CertRefUtils$1: Verification failed for property 'SigningCertificate': Invalid issue name: C=CO, L=Bogota D.C., O=Andes SCD., OU=Division de certificacion entidad final, CN=CA ANDES SCD S.A. Clase II, E=info@andesscd.com.co

And this other its ok at the validation:

<ds:X509IssuerName>
C=CO,L=Bogota D.C.,O=Andes SCD.,OU=Division de certificacion entidad final,CN=CA ANDES SCD S.A. Clase II,1.2.840.113549.1.9.1=#1614696e666f40616e6465737363642e636f6d2e636f
</ds:X509IssuerName>

What is the error in the first issuername info?

Thanks.

**Comment by luisgoncalves** [comment]
Hello,

Can you provide the full stack trace?

**Comment by luisgoncalves** [comment]
The exception is being thrown by the code in the line below, which parses the issuer DN:

https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/verification/CertRefUtils.java#L47

From the documentation of `new X500Principal(String)` (see [here](https://docs.oracle.com/javase/7/docs/api/javax/security/auth/x500/X500Principal.html#X500Principal(java.lang.String))) it seems that the support keyword for emails is `EMAILADDRESS` instead of `E`...

I don't know if `E` is a valid keyword in some scenario or if there is a better way to parse those DNs, but for now this really isn't a bug. If you have an improvement to the current processing, feel free to open a PR.

**Comment by nekkiy** [comment]
Hello. I created branch https://github.com/nekkiy/xades4j/tree/iss157 for this problem ([test with fix](https://github.com/nekkiy/xades4j/blob/iss157/src/test/java/xades4j/utils/Issue157Test.java)). But i not created PR, because i don't sure that  `E` is a valid keyword. This is probably a bug related to the use [BCStyle](https://github.com/bcgit/bc-java/blob/r1v60/core/src/main/java/org/bouncycastle/asn1/x500/style/BCStyle.java#L207). Moreover, I did not find information about the attribute with the name `E`. [According to the search](http://www.oid-info.com/cgi-bin/display?oid=1.2.840.113549.1.9.1&action=display), the name of the attribute with the OID `1.2.840.113549.1.9.1` is `emailAddress`.

However, you gave me a few thoughts on what should be given the opportunity to expand the number of valid attributes, i.e. go to the use of the constructor [X500Principal(java.lang.String,java.util.Map)](https://docs.oracle.com/javase/7/docs/api/javax/security/auth/x500/X500Principal.html#X500Principal(java.lang.String,%20java.util.Map)) instead of [X500Principal(java.lang.String)](https://docs.oracle.com/javase/7/docs/api/javax/security/auth/x500/X500Principal.html#X500Principal(java.lang.String)). This will allow more compliance with the [RFC4514 specification, Section 2.3](https://tools.ietf.org/html/rfc4514#section-2.3).

> Implementations are not expected to dynamically update their
   knowledge of registered short names.  However, implementations SHOULD
   provide a mechanism to allow their knowledge of registered short
   names to be updated.

**Comment by luisgoncalves** [comment]
Hi @nekkiy. Reopening, since your suggestion is something that could be interesting.

However, we'd have to find another way to register the mappings (without static methods). I think that, ideally, they would be registered in the initial configuration. Just have to review the places were usage is needed and think about how to get the mappings there (if DI fits).

Also `RfcUtils` starts to feel like a very generic name. Specifically, for `X500Principal`-related operations, we could have a class with a name that reflects that scope.

**Comment by nekkiy** [comment]
Hello @luisgoncalves. I created update patch. However, I thinking we need to do few global changes:

- reorganizate system  of exceptions 
- more use  BouncyCastle API (org.bouncycastle.asn1.x500.X500Name instead javax.security.auth.x500.X500Principal and etc). 

What do you say about this?

I will created PR after you do review my patch.
