### ISSUE TITLE
make signature in xades-epes with php -  digital signature DIAN

### ISSUE THREAD

**Issue by jph9184** [luisgoncalves/xades4j#171]
Good Morning,
Someone has been able to make the digital signature for Colombia in PHP.
I would appreciate it if you would help me since I am on time

 Thanks you

**Comment by luisgoncalves** [comment]
Hi @jph9184.

This isn't the best/proper place to ask for this kind of help, since:

- You aren't presenting an issue with the xades4j library.
- xades4j is a Java project, and you are asking for help with PHP.
- People that eventually could help you won't get notifications of the creation of this issue and it's not likely that many people are proactively checking the issues on the project.
- DIAN uses this library in they signature validation service; this doesn't mean that this issue tracker is the proper place to ask for help consuming their service.

That said, there as been a lot of discussion on other tickets, and I think some  folks were trying to use PHP:

- #134 
- #151 

Other than thin, your best option is probably asking in Stackoverflow.
