### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by aaronsaescobar** [luisgoncalves/xades4j#179]
I try to build the aplication and recived this error xades4j.verification.TimeStampInvalidSignatureException: Verification failed for property 'SignatureTimeStamp': invalid token signature. I use java 7 and maven 3.6

**Comment by aaronsaescobar** [comment]
thx but the problem persist after the update. if you need something let me know

![captura](https://user-images.githubusercontent.com/44914266/48306129-df5ae380-e4fb-11e8-817b-7ffabc5db1fb.PNG)

**Comment by luisgoncalves** [comment]
That's weird.. The CI build succeeded: https://travis-ci.org/luisgoncalves/xades4j/builds/453100563.

Which JVM are you using? Oracle?

**Comment by aaronsaescobar** [comment]
![captura1](https://user-images.githubusercontent.com/44914266/48306909-71b4b480-e507-11e8-9b0e-cfff3fcc5c18.PNG)

**Comment by luisgoncalves** [comment]
I tried running a CI build using ORacle JDK 7, however I got some errors related to maven: https://travis-ci.org/luisgoncalves/xades4j/jobs/453537292. The Travis VMs supporting Oracle JDK 7 are older and maybe this is some incompatibility with installed maven version. Since Oracle JDK 7 reached EOL long time ago, I'm not willing to spend much time after this. 

On my development environment all the tests pass. I'm on Windows 10 with Oracle JDK 8. Maybe you could upgrade to JDK 8 and test again? Otherwise I'll have to ask you to debug this yourself. A good point to start debugging would be `SignatureTimeStampVerifier`.

**Comment by aaronsaescobar** [comment]
thx for you advice, i changed the JDK to 1.8.0_151 but i have this error.

![captura1](https://user-images.githubusercontent.com/44914266/48318097-1cd57480-e5c1-11e8-9b8c-c32ea4d1da9a.PNG)

**Comment by luisgoncalves** [comment]
@aaronsaescobar this problem should be fixed now: https://travis-ci.org/luisgoncalves/xades4j/builds/456594271.

Reopen if something else comes up related to test execution.

**Comment by andrengine** [comment]
hello this is a test

**Comment by andrengine** [comment]
Hello @luisgoncalves,

First of all, I want to thank you for all your help on the signature issue. Yesterday I was able to sign correctly, following the instructions at https://github.com/luisgoncalves/xades4j/issues/134.

By looking at the signed XML, I get the keyinfo tag like this:

<ds: KeyInfo>

But I need it this way:

<ds: KeyInfo Id = "xmldsig-50680329-cdf3-4bb7-9d8f-edd480c8019c-keyinfo">

This id would be the public key? ist'n it ? and I was wondering if I made a mistake because this id did not "appear" automatically ...

Could you help me with some directions? Thank you.

**Comment by luisgoncalves** [comment]
> This id would be the public key? ist'n it ? and I was wondering if I made a mistake because this id did not "appear" automatically ...

No, it is a unique identifier for the `KeyInfo` element. This ID is only added by xades4j when you request to include the `KeyInfo` element in the signature (a `Reference` is added pointing to it). Check the [wiki](https://github.com/luisgoncalves/xades4j/wiki/OtherSigningOptions#keyinfo-content) and the [docs](http://luisgoncalves.github.io/xades4j/javadocs/1.5.0/reference/xades4j/production/BasicSignatureOptions.html#signKeyInfo(boolean)).

**Comment by andrengine** [comment]
thank you I think I got it, I made this:

// Role
        XadesSigner  signer = (XadesSigner ) new XadesEpesSigningProfile(kdp, policyInfoProvider).withBasicSignatureOptions(new BasicSignatureOptions().signKeyInfo(true))
                   .withSignaturePropertiesProvider(new SignaturePropertiesProvider() {...}

I took this code from https://github.com/luisgoncalves/xades4j/issues/134, and add  the ".withBasicSignatureOptions(new BasicSignatureOptions().signKeyInfo(true))"part. This reference is for somedy else tha need it.

I am goning to test it with the webservice, thanks again.

**Comment by andrengine** [comment]
Mmm.. last one thing, when in netbeans 11 and jdk 8, one clean and build, you get this error:

testVerifyBESExtrnlResEnrichC(xades4j.verification.XadesVerifierImplTest)  Time elapsed: 0.752 sec  <<< ERROR!
xades4j.verification.TimeStampInvalidSignatureException: Verification failed for property 'SignatureTimeStamp': invalid token signature


But just runing works....

**Comment by andrengine** [comment]
Hi @luisgoncalves,

After a lot of tests and solving other issues, I am having a problem when try to "addressing".

This is, in the "wsa:To" tag I have to add an Id in this way:

<wsa:To wsu:Id="id-EA5626A87AC3DFFF9A1588799952181228" 

And this Id is referenced from the reference tag inside the security tag, in this way:

<ds:Reference URI="#id-EA5626A87AC3DFFF9A1588799952181228">

With the others id, I can modify them, but with this particular Id I get an error afther any change.

Honestly I am stuck here, I have been making a lot of research to understand the Id meaning and how to manage it with no luck....

Coud you help me with some directions ? thanks.

**Comment by luisgoncalves** [comment]
@andrengine 

I'm not sure I understand, but if that `wsa:To` tag is just another element in your XML doc, add the ID to it using the DOM APIs and then add an additional `DataObjectReference` using "#id" when calling the xades4j signer. This will add the additional  `Reference`.

**Comment by andrengine** [comment]
Hi @luisgoncalves, thanks for your answer,

Ok, I can do that, but this structure "id-EA5626A87AC3DFFF9A1588799952181228" and particularly this 34 character sequence: EA5626A87AC3DFFF9A1588799952181228, how can I generated it?. This is what I've been researching but can't find the specs.

**Comment by luisgoncalves** [comment]
I don't know. That seems to be something specific to your use-case. Some questions for thought: where did you get that ID? Isn't it a unique/random value generated in some other context? 
This isn't related to xades4j anymore nor to this specific issue. I probably can't help you anymore.
