### ISSUE TITLE
xades4j.verification.ReferenceValueException: Reference '' cannot be validated

### ISSUE THREAD

**Issue by jhon3724** [luisgoncalves/xades4j#187]
Greetings @luisgoncalves ,

I am trying to perform the Electronic Billing process of the DIAN, signing the XML document with a certificate acquired through an Entity accredited by the ONAC, but at the time of consulting the result of the process, I see an error in the validation of the firm:

com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.ReferenceValueException: Reference '' cannot be validated

I have tried to sign the document, based on other issues, but the error persists.

Attach the signed XML,

I appreciate any help you can give me.

[ws_f08001674940980000048.zip](https://github.com/luisgoncalves/xades4j/files/3023861/ws_f08001674940980000048.zip)

**Comment by luisgoncalves** [comment]
Hello,

As I said already many times when people report situations similar to the one you have, this isn't usually a problem with xades4j. The fact that DIAN uses xades4j on their service doesn't turn this issue tracker into the proper place for support.

Also, providing only the signed XML isn't very helpful; since the service error says that a reference's value cannot be validated, it probably means that you are building it in the wrong way. Do you have some code using xades4j to produce the signature that you can show?
