### ISSUE TITLE
DIAN VALIDACION PREVIA

### ISSUE THREAD

**Issue by ricposace** [luisgoncalves/xades4j#196]
Hello Luis

I'm trying to sign xml documents for Colombian Taxes aurtority DIAN using xades4j version 1.5.1.

I have a signed xml document that passes all test and a xml document signed with xades4j that don't. I've identified some differences between the 2 xmls.  The first one is:

xml approved:
-----------------------
<xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#" Target="#xmldsig-c61ed635-4081-40ec-a509-fa248af9f909">
							<xades:SignedProperties Id="xmldsig-c61ed635-4081-40ec-a509-fa248af9f909-signedprops">
-----------------------

xml xades4j 
-----------------------
<xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#" Target="#xmldsig-ef52a51f-4f12-403c-b668-6d566412e207">
<ns0:SignedProperties xmlns:ns0="http://uri.etsi.org/01903/v1.3.2#" xmlns:ns1="http://www.w3.org/2000/09/xmldsig#" xmlns:ns2="http://uri.etsi.org/01903/v1.4.1#" Id="xmldsig-ef52a51f-4f12-403c-b668-6d566412e207-signedprops">
------------

In the xades4j xml the name definitions are duplicated in tags QualifyingProperties  and  SignedProperties whit diferent name spaces.

How can I remove duplicate definitions and force inner tags to use  xmlns:xades name space?
[xml.zip](https://github.com/luisgoncalves/xades4j/files/3552808/xml.zip)

**Comment by luisgoncalves** [comment]
@ricposace xades4j doesn't do anything explicit to add those dupplicates... If they are being added it's probably because the DOM document doesn't know about those namespaces yet. Are you setting the DocumentFactory to be namespace aware when loading the XML DOM Document?

Even though it looks bad, the presence of the duplicate namespace declarations doesn't make the XML invalid...

**Comment by ricposace** [comment]
this is code for document factory

        Document doc = null;
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setNamespaceAware(true);
        ByteArrayInputStream inStreamXMLElement = new ByteArrayInputStream(xml);
        InputSource is = new InputSource(new InputStreamReader(inStreamXMLElement));

**Comment by luisgoncalves** [comment]
Looks good at a glance.. Are sure that the validation error is related to those NS declarations?

Anyway, I have signed files generated with xades4j that don't have those duplicates.. Maybe this is related to some different Java, JAXB, etc versions/implementations? Which versions/platforms are you on?

**Comment by ricposace** [comment]
Hello Luis

The error is "SIGNPLGNS".  I'm guessing that the problem is about name spaces

<s:Body>
      <SendBillSyncResponse xmlns="http://wcf.dian.colombia">
         <SendBillSyncResult xmlns:b="http://schemas.datacontract.org/2004/07/DianResponse" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <b:ErrorMessage xmlns:c="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
               <c:string>Regla: SIGNPLGNS, Rechazo: No se pudo validar firma.</c:string>
            </b:ErrorMessage>
            <b:IsValid>false</b:IsValid>
            <b:StatusCode>99</b:StatusCode>
            <b:StatusDescription>Validación contiene errores en campos mandatorios.</b:StatusDescription>
            <b:StatusMessage i:nil="true"/>
        
            <b:XmlBytes i:nil="true"/>
            <b:XmlFileName>face_f0900127105003B0233B1</b:XmlFileName>
         </SendBillSyncResult>
      </SendBillSyncResponse>
   </s:Body>

**Comment by luisgoncalves** [comment]
I suggested trying to confirm what exactly does the error mean, since the NS declarations are cosmetic more than anything else.

Still, regarding the NS declarations, I'm throwing out some pointers, as I have no clue what's causing it. Maybe you can try to pin point the issue:

- The prefixes are configured globally here: https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/production/Init.java.
- The qualifying properties element is created here: https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/production/SignerBES.java#L187.
- JAXB is used to marshal the XML into the node created above: https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/xml/marshalling/BaseJAXBMarshaller.java
- I just executed the lib tests to have some sample signed files and they don't have the issue (see attached sample). I'm on Java 1.8.0_221 Win64 

[document.signed.bes.txt](https://github.com/luisgoncalves/xades4j/files/3553208/document.signed.bes.txt)

**Comment by ricposace** [comment]
Hello Luis

Can you tell me which version of libraries you are using?. I've recently update jar to this ones:
aopalliance-1.0.jar
bcpkix-jdk15on-1.62.jar
bcprov-jdk15on-1.62.jar
guice-2.0.jar
guice-multibindings-2.0.jar
slf4j-api-1.7.28.jar
slf4j-log4j12-1.7.28.jar
xades4j-1.5.1.jar
xmlsec-2.0.9.jar

Maybe that's the problem

Thank you

**Comment by luisgoncalves** [comment]
The only relevant diff for the base xades4j dependencies is BC, but I don't think it would create issues ith XML NS.

**Comment by luisgoncalves** [comment]
Did you come to any conclusion on this issue?

**Comment by edanco77** [comment]
Luis good morning, to consume the DIAN web service must be done with WS-Security 1.0 Oasis, with the X.509 Certificate Token Profile 1.1 authentication, I am trying to do it but I still have not been able, have you done something similar? Or can you help me check my code?

Thank you.

**Comment by ricposace** [comment]
Hello Luis

Yes, I managed to get it working, the problem is library "xmlsec". if you use version over 2.0.0.  duplicate name spaces.

I'm using xmlsec-1.4.2

Thank you very much.
