### ISSUE TITLE
NoSuchMethodFound when using Apache xmlsec 2.2.0

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [luisgoncalves/xades4j#207]
the current version does not support the newest version of apache xmlsec 2.2.0

There is a `NoSuchMethodFoundError` in `QualifyingPropertyVerificationContext`

`XMLSignatureInput refData = ResourceResolver.getInstance(refAttr, "", true).resolve(refAttr, "", true);`

**Comment by luisgoncalves** [comment]
In the Apache Santuario news one can read:

> Version 2.2.0 of the Apache XML Security for Java library has been released. This is a new major release

Being a major release (despite the versioning...) it's normal that there are breaking changes. In the [release notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311231&version=12344983) many other refactorings are mentioned, which may require codes changes in xades4j if upgrading. Since Santuario 2.1.X is also a "current" version, I'm not sure there's a reason to update xades4j immediately. I'd have to see if the bugs fixed and improvements are beneficial.

**Comment by runeflobakk** [comment]
Just for added information. `ResourceResolver` seems to have been [refactored](https://github.com/apache/santuario-xml-security-java/commit/fc0df2d6cdcf1ea023f0aab53a68244fcea911df) in xmlsec 2.2.0, to be more oriented around SPI and resolving global `ResourceResolverSpi` instances. As such, it does not seem appropriate for `SignatureSpecificVerificationOptions.useResourceResolver(..)` to accept a `ResourceResolver` as an argument, but should maybe accept a `ResourceResolverSpi` instead?

**Comment by luisgoncalves** [comment]
Apache xmlsec dependency has been updated.
