### ISSUE TITLE
javax/xml/bind/JAXBException  SoapUI

### ISSUE THREAD

**Issue by rafalsza** [luisgoncalves/xades4j#212]
Hi
On a latest SoapUI version 5.6.0 I have a problem with signing documents.
log :  xades4j.utils.XadesProfileResolutionException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
java jdk 14.0.2
libraries: xades4j-1.5.1,xmlsec-2.0.9

**Comment by luisgoncalves** [comment]
JAXB is no longer included in the JDK (since version 11). This requires further investigation for options.

- https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/
- https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio
- Example failed build in xades4j: https://travis-ci.org/github/luisgoncalves/xades4j/jobs/736860138

**Comment by rafalsza** [comment]
Thank you. After adding these 3 libraries 
![obraz](https://user-images.githubusercontent.com/59625640/96465861-bf74e400-1229-11eb-8e94-00c63f5ccbc2.png)
everything works
