### ISSUE TITLE
Update usage of deprecated BouncyCastle API in 1.50+

### ISSUE THREAD

**Issue by mlundblad** [luisgoncalves/xades4j#96]
Hi!

In the SignServer project we are using XAdES4J for supplying XAdES XML signing support.
We are in the process of upgrading our BouncyCastle dependency to 1.53.
I have rebuilt XAdES4J using BC 1.53, and will be supplying a patch file with the changes we have made.
[bc153.txt](https://github.com/luisgoncalves/xades4j/files/48542/bc153.txt)

**Comment by beat2** [comment]
Hi

We had the opposite requirement, and had to downgrade to BC 1.4.5 (because of we are still using iText 2.1.7 which is only compatible with that).

Would it be possible to split out the implementations of the TSA-Interfaces into maven submodules? Then the main module would not be dependent on BC at all.

Cheers, beat

**Comment by luisgoncalves** [comment]
@beat2 That's an idea worth exploring. But will need to consider some features that are not yet implemented and might required BC (e.g. OCSP support)

**Comment by beat2** [comment]
@luisgoncalves Then again, one could have the interface in the main module and the implementation in the "provider-impl" module. Somewhat related, if you need an example for OCSP with BC, there is an implementation in iText 2.1.7. For later versions you might check first if the licenses are compatbile.

**Comment by luisgoncalves** [comment]
Since the lib is already on 1.50, I'll update to 1.5X. Separating the provider implementations into different modules is another subject.
